# Generated by Django 3.2.12 on 2022-02-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooktbl',
            fields=[
                ('recipeid', models.AutoField(db_column='recipeID', primary_key=True, serialize=False)),
                ('recipename', models.CharField(blank=True, db_column='recipeName', max_length=20, null=True)),
                ('recipedetail', models.TextField(blank=True, db_column='recipeDetail', null=True)),
                ('recipetype', models.CharField(blank=True, db_column='recipeType', max_length=5, null=True)),
            ],
            options={
                'db_table': 'cookTBL',
                'managed': False,
            },
        ),
    ]
