# Generated by Django 3.2.12 on 2022-02-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_cooktbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='List2Tbl',
            fields=[
                ('listid', models.AutoField(db_column='listID', primary_key=True, serialize=False)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'list2TBL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='List3Tbl',
            fields=[
                ('listid', models.AutoField(db_column='listID', primary_key=True, serialize=False)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'list3TBL',
                'managed': False,
            },
        ),
    ]
