# Generated by Django 3.2.12 on 2022-02-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_list2tbl_list3tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userrecingtbl',
            fields=[
                ('urecingid', models.AutoField(db_column='uRecIngID', primary_key=True, serialize=False)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'userRecIngTBL',
                'managed': False,
            },
        ),
    ]
